### ISSUE TITLE
Automatic Firmware Update

### ISSUE THREAD

**Issue by ChrisVeigl** [asterics/FLipMouse#37]
it would be great if we could enable automatic firmware updates for the BT-Add-On from the GUI (as it exists already for the Teensy firmware)

Theoretically it could work if we replace the second GND signal from the AUX connector with a connection to GPIO0 of the ESP32 and add a way to reset the ESP32 (maybe using an analog circuit)?
 
Then, we could forward the serial communication during the FW-upload from esptool to the ESP32 via the TeensyLC....

**Comment by benjaminaigner** [comment]
IMHO we need:
1. detect esptool.py DTR/RTS behaviour
2. redirect DTR/RTS lines to GPIO0 & RESET lines of ESP32 (I think we should route both signals of the ESP32miniBT module to the AUX header and remove the buttons from the PCB)
3. route the USB serial data directly to the ESP32 module

One question still exists:
How to use the UART interfaces? programming the ESP32 is done via UART0 as well as the debug output.
The communication between Teensy and ESP32 is done via UART2.

Options:
* Write own bootloader
* Route both UARTs from ESP32 to AUX header -> Software Serial necessary because we don't have full Teensy serial port on AUX header (only TX2).
* Write some kind of OTA firmware, without changing the PCB at all

**Comment by benjaminaigner** [comment]
I think the most compatible way with the current PCB & firmware would be the OTA way:

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/ota.html

We could use one of the examples, but instead of updating via HTTP(s) we could use the data from UART.

Nevertheless, hopefully the Flash memory of the Teensy allows such changes :-)

**Comment by benjaminaigner** [comment]
Closed a few years ago :-), see: https://github.com/asterics/esp32_addon_bootloader
